### ISSUE TITLE
Update to latest fix

### ISSUE THREAD

**Issue by rjuszczyk** [jzaccone/SlidingMenu-aar#2]
In this version there is StackOverflowError which was fixed 7 months ago. Could you update this repository (last update 9months ago) to newest sliding library code (https://github.com/sysu2012zzp/SlidingMenu/commit/1d84040914b645ab836c8b02cbd0747ad3dedc66)?

**Comment by ziem** [comment]
+1

**Comment by btwarog** [comment]
+1

**Comment by asolis90** [comment]
+1

**Comment by jzaccone** [comment]
Fixed in latest commit
