### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by maelfosso** [jzaccone/SlidingMenu-aar#3]
How to install SlidingMenu with Gradle ?

I follow your instructions about build.gradle file. In my one, I don't see maven anywhere just jcenter().

**Comment by halil** [comment]
``` gradle
allprojects {
    repositories {
        jcenter()
        maven {
            url "http://jzaccone.github.io/SlidingMenu-aar"
        }
    }
}
```

**Comment by jzaccone** [comment]
Thanks @hibrahimsafak @mafcm Let me know if this didn't work for you
